-- ==============================================
-- 金纸兼容性数据插入脚本（基于图片实际数据）
-- 插入到pre_processing_steps表中
-- 基于图片中的实际兼容性数据，包含√和X状态
-- ==============================================

INSERT INTO pre_processing_steps (step_name, series_name, product_id, step_order, is_active, description, status, paper_type) VALUES

-- 印刷/过油面兼容性数据
-- 普通油墨 - 所有系列兼容
('普通油墨', 'SY1-系列', NULL, 1, TRUE, '普通油墨印刷兼容性', 'V', '普通金纸'),
('普通油墨', 'SY6-系列', NULL, 1, TRUE, '普通油墨印刷兼容性', 'V', '普通金纸'),
('普通油墨', 'SY6 系列', NULL, 1, TRUE, '普通油墨印刷兼容性', 'V', '普通金纸'),
('普通油墨', 'SY6+系列', NULL, 1, TRUE, '普通油墨印刷兼容性', 'V', '普通金纸'),
('普通油墨', 'SSY6 系列', NULL, 1, TRUE, '普通油墨印刷兼容性', 'V', '普通金纸'),
('普通油墨', 'G1 系列', NULL, 1, TRUE, '普通油墨印刷兼容性', 'V', '普通金纸'),
('普通油墨', 'SA 系列', NULL, 1, TRUE, '普通油墨印刷兼容性', 'V', '普通金纸'),
('普通油墨', 'SB 系列', NULL, 1, TRUE, '普通油墨印刷兼容性', 'V', '普通金纸'),
('普通油墨', 'TA', NULL, 1, TRUE, '普通油墨印刷兼容性', 'V', '普通金纸'),
('普通油墨', 'TB', NULL, 1, TRUE, '普通油墨印刷兼容性', 'V', '普通金纸'),
('普通油墨', 'S19 系列', NULL, 1, TRUE, '普通油墨印刷兼容性', 'V', '普通金纸'),
('普通油墨', 'A19', NULL, 1, TRUE, '普通油墨印刷兼容性', 'V', '普通金纸'),
('普通油墨', 'AF', NULL, 1, TRUE, '普通油墨印刷兼容性', 'V', '普通金纸'),
('普通油墨', 'SP', NULL, 1, TRUE, '普通油墨印刷兼容性', 'V', '普通金纸'),
('普通油墨', 'KA 系列', NULL, 1, TRUE, '普通油墨印刷兼容性', 'V', '普通金纸'),
('普通油墨', 'KB 系列', NULL, 1, TRUE, '普通油墨印刷兼容性', 'V', '普通金纸'),
('普通油墨', 'L817/GB系列', NULL, 1, TRUE, '普通油墨印刷兼容性', 'V', '普通耐磨'),
('普通油墨', 'E8系列', NULL, 1, TRUE, '普通油墨印刷兼容性', 'V', '普通耐磨'),
('普通油墨', 'ST系列', NULL, 1, TRUE, '普通油墨印刷兼容性', 'V', '普通耐磨'),
('普通油墨', 'SST 系列', NULL, 1, TRUE, '普通油墨印刷兼容性', 'V', '普通耐磨'),
('普通油墨', 'GN 系列', NULL, 1, TRUE, '普通油墨印刷兼容性', 'V', '普通耐磨'),
('普通油墨', 'GN2 系列', NULL, 1, TRUE, '普通油墨印刷兼容性', 'V', '普通耐磨'),
('普通油墨', 'TB815系列', NULL, 1, TRUE, '普通油墨印刷兼容性', 'V', '高耐磨'),
('普通油墨', 'LA 系列', NULL, 1, TRUE, '普通油墨印刷兼容性', 'V', '鐳射燙金紙'),
('普通油墨', 'LLW 系列', NULL, 1, TRUE, '普通油墨印刷兼容性', 'V', '鐳射燙金紙'),
('普通油墨', 'LLO 系列', NULL, 1, TRUE, '普通油墨印刷兼容性', 'V', '鐳射燙金紙'),
('普通油墨', 'KM 系列', NULL, 1, TRUE, '普通油墨印刷兼容性', 'V', '鐳射燙金紙'),
('普通油墨', 'G6系列', NULL, 1, TRUE, '普通油墨印刷兼容性', 'V', '鐳射燙金紙'),
('普通油墨', 'API 系列', NULL, 1, TRUE, '普通油墨印刷兼容性', 'V', '色箔'),
('普通油墨', 'V系列', NULL, 1, TRUE, '普通油墨印刷兼容性', 'V', '色箔'),
('普通油墨', 'VB系列', NULL, 1, TRUE, '普通油墨印刷兼容性', 'V', '色箔'),
('普通油墨', 'YZT 鐳射系列', NULL, 1, TRUE, '普通油墨印刷兼容性', 'V', '客人指定'),
('普通油墨', 'YZT 普通系列', NULL, 1, TRUE, '普通油墨印刷兼容性', 'V', '客人指定'),

-- LED UV墨 - 所有系列兼容
('LED UV墨', 'SY1-系列', NULL, 2, TRUE, 'LED UV墨印刷兼容性', 'V', '普通金纸'),
('LED UV墨', 'SY6-系列', NULL, 2, TRUE, 'LED UV墨印刷兼容性', 'V', '普通金纸'),
('LED UV墨', 'SY6 系列', NULL, 2, TRUE, 'LED UV墨印刷兼容性', 'V', '普通金纸'),
('LED UV墨', 'SY6+系列', NULL, 2, TRUE, 'LED UV墨印刷兼容性', 'V', '普通金纸'),
('LED UV墨', 'SSY6 系列', NULL, 2, TRUE, 'LED UV墨印刷兼容性', 'V', '普通金纸'),
('LED UV墨', 'G1 系列', NULL, 2, TRUE, 'LED UV墨印刷兼容性', 'V', '普通金纸'),
('LED UV墨', 'SA 系列', NULL, 2, TRUE, 'LED UV墨印刷兼容性', 'V', '普通金纸'),
('LED UV墨', 'SB 系列', NULL, 2, TRUE, 'LED UV墨印刷兼容性', 'V', '普通金纸'),
('LED UV墨', 'TA', NULL, 2, TRUE, 'LED UV墨印刷兼容性', 'V', '普通金纸'),
('LED UV墨', 'TB', NULL, 2, TRUE, 'LED UV墨印刷兼容性', 'V', '普通金纸'),
('LED UV墨', 'S19 系列', NULL, 2, TRUE, 'LED UV墨印刷兼容性', 'V', '普通金纸'),
('LED UV墨', 'A19', NULL, 2, TRUE, 'LED UV墨印刷兼容性', 'V', '普通金纸'),
('LED UV墨', 'AF', NULL, 2, TRUE, 'LED UV墨印刷兼容性', 'V', '普通金纸'),
('LED UV墨', 'SP', NULL, 2, TRUE, 'LED UV墨印刷兼容性', 'V', '普通金纸'),
('LED UV墨', 'KA 系列', NULL, 2, TRUE, 'LED UV墨印刷兼容性', 'V', '普通金纸'),
('LED UV墨', 'KB 系列', NULL, 2, TRUE, 'LED UV墨印刷兼容性', 'V', '普通金纸'),
('LED UV墨', 'L817/GB系列', NULL, 2, TRUE, 'LED UV墨印刷兼容性', 'V', '普通耐磨'),
('LED UV墨', 'E8系列', NULL, 2, TRUE, 'LED UV墨印刷兼容性', 'V', '普通耐磨'),
('LED UV墨', 'ST系列', NULL, 2, TRUE, 'LED UV墨印刷兼容性', 'V', '普通耐磨'),
('LED UV墨', 'SST 系列', NULL, 2, TRUE, 'LED UV墨印刷兼容性', 'V', '普通耐磨'),
('LED UV墨', 'GN 系列', NULL, 2, TRUE, 'LED UV墨印刷兼容性', 'V', '普通耐磨'),
('LED UV墨', 'GN2 系列', NULL, 2, TRUE, 'LED UV墨印刷兼容性', 'V', '普通耐磨'),
('LED UV墨', 'TB815系列', NULL, 2, TRUE, 'LED UV墨印刷兼容性', 'V', '高耐磨'),
('LED UV墨', 'LA 系列', NULL, 2, TRUE, 'LED UV墨印刷兼容性', 'V', '鐳射燙金紙'),
('LED UV墨', 'LLW 系列', NULL, 2, TRUE, 'LED UV墨印刷兼容性', 'V', '鐳射燙金紙'),
('LED UV墨', 'LLO 系列', NULL, 2, TRUE, 'LED UV墨印刷兼容性', 'V', '鐳射燙金紙'),
('LED UV墨', 'KM 系列', NULL, 2, TRUE, 'LED UV墨印刷兼容性', 'V', '鐳射燙金紙'),
('LED UV墨', 'G6系列', NULL, 2, TRUE, 'LED UV墨印刷兼容性', 'V', '鐳射燙金紙'),
('LED UV墨', 'API 系列', NULL, 2, TRUE, 'LED UV墨印刷兼容性', 'V', '色箔'),
('LED UV墨', 'V系列', NULL, 2, TRUE, 'LED UV墨印刷兼容性', 'V', '色箔'),
('LED UV墨', 'VB系列', NULL, 2, TRUE, 'LED UV墨印刷兼容性', 'V', '色箔'),
('LED UV墨', 'YZT 鐳射系列', NULL, 2, TRUE, 'LED UV墨印刷兼容性', 'V', '客人指定'),
('LED UV墨', 'YZT 普通系列', NULL, 2, TRUE, 'LED UV墨印刷兼容性', 'V', '客人指定'),

-- 水油-光/啞/半光啞 - 所有系列兼容
('水油-光/啞/半光啞', 'SY1-系列', NULL, 3, TRUE, '水油-光/哑/半光哑印刷兼容性', 'V'),
('水油-光/啞/半光啞', 'SY6-系列', NULL, 3, TRUE, '水油-光/哑/半光哑印刷兼容性', 'V'),
('水油-光/啞/半光啞', 'SY6 系列', NULL, 3, TRUE, '水油-光/哑/半光哑印刷兼容性', 'V'),
('水油-光/啞/半光啞', 'SY6+系列', NULL, 3, TRUE, '水油-光/哑/半光哑印刷兼容性', 'V'),
('水油-光/啞/半光啞', 'SSY6 系列', NULL, 3, TRUE, '水油-光/哑/半光哑印刷兼容性', 'V'),
('水油-光/啞/半光啞', 'G1 系列', NULL, 3, TRUE, '水油-光/哑/半光哑印刷兼容性', 'V'),
('水油-光/啞/半光啞', 'SA 系列', NULL, 3, TRUE, '水油-光/哑/半光哑印刷兼容性', 'V'),
('水油-光/啞/半光啞', 'SB 系列', NULL, 3, TRUE, '水油-光/哑/半光哑印刷兼容性', 'V'),
('水油-光/啞/半光啞', 'TA', NULL, 3, TRUE, '水油-光/哑/半光哑印刷兼容性', 'V'),
('水油-光/啞/半光啞', 'TB', NULL, 3, TRUE, '水油-光/哑/半光哑印刷兼容性', 'V'),
('水油-光/啞/半光啞', 'S19 系列', NULL, 3, TRUE, '水油-光/哑/半光哑印刷兼容性', 'V'),
('水油-光/啞/半光啞', 'A19', NULL, 3, TRUE, '水油-光/哑/半光哑印刷兼容性', 'V'),
('水油-光/啞/半光啞', 'AF', NULL, 3, TRUE, '水油-光/哑/半光哑印刷兼容性', 'V'),
('水油-光/啞/半光啞', 'SP', NULL, 3, TRUE, '水油-光/哑/半光哑印刷兼容性', 'V'),
('水油-光/啞/半光啞', 'KA 系列', NULL, 3, TRUE, '水油-光/哑/半光哑印刷兼容性', 'V'),
('水油-光/啞/半光啞', 'KB 系列', NULL, 3, TRUE, '水油-光/哑/半光哑印刷兼容性', 'V'),
('水油-光/啞/半光啞', 'L817/GB系列', NULL, 3, TRUE, '水油-光/哑/半光哑印刷兼容性', 'V'),
('水油-光/啞/半光啞', 'E8系列', NULL, 3, TRUE, '水油-光/哑/半光哑印刷兼容性', 'V'),
('水油-光/啞/半光啞', 'ST系列', NULL, 3, TRUE, '水油-光/哑/半光哑印刷兼容性', 'V'),
('水油-光/啞/半光啞', 'SST 系列', NULL, 3, TRUE, '水油-光/哑/半光哑印刷兼容性', 'V'),
('水油-光/啞/半光啞', 'GN 系列', NULL, 3, TRUE, '水油-光/哑/半光哑印刷兼容性', 'V'),
('水油-光/啞/半光啞', 'GN2 系列', NULL, 3, TRUE, '水油-光/哑/半光哑印刷兼容性', 'V'),
('水油-光/啞/半光啞', 'TB815系列', NULL, 3, TRUE, '水油-光/哑/半光哑印刷兼容性', 'V'),
('水油-光/啞/半光啞', 'LA 系列', NULL, 3, TRUE, '水油-光/哑/半光哑印刷兼容性', 'V'),
('水油-光/啞/半光啞', 'LLW 系列', NULL, 3, TRUE, '水油-光/哑/半光哑印刷兼容性', 'V'),
('水油-光/啞/半光啞', 'LLO 系列', NULL, 3, TRUE, '水油-光/哑/半光哑印刷兼容性', 'V'),
('水油-光/啞/半光啞', 'KM 系列', NULL, 3, TRUE, '水油-光/哑/半光哑印刷兼容性', 'V'),
('水油-光/啞/半光啞', 'G6系列', NULL, 3, TRUE, '水油-光/哑/半光哑印刷兼容性', 'V'),
('水油-光/啞/半光啞', 'API 系列', NULL, 3, TRUE, '水油-光/哑/半光哑印刷兼容性', 'V'),
('水油-光/啞/半光啞', 'V系列', NULL, 3, TRUE, '水油-光/哑/半光哑印刷兼容性', 'V'),
('水油-光/啞/半光啞', 'VB系列', NULL, 3, TRUE, '水油-光/哑/半光哑印刷兼容性', 'V'),
('水油-光/啞/半光啞', 'YZT 鐳射系列', NULL, 3, TRUE, '水油-光/哑/半光哑印刷兼容性', 'V'),
('水油-光/啞/半光啞', 'YZT 普通系列', NULL, 3, TRUE, '水油-光/哑/半光哑印刷兼容性', 'V'),

-- GP-LED 光油/GP-LED 啞油 - 所有系列兼容
('GP-LED 光油/GP-LED 啞油', 'SY1-系列', NULL, 4, TRUE, 'GP-LED 光油/GP-LED 哑油印刷兼容性', 'V'),
('GP-LED 光油/GP-LED 啞油', 'SY6-系列', NULL, 4, TRUE, 'GP-LED 光油/GP-LED 哑油印刷兼容性', 'V'),
('GP-LED 光油/GP-LED 啞油', 'SY6 系列', NULL, 4, TRUE, 'GP-LED 光油/GP-LED 哑油印刷兼容性', 'V'),
('GP-LED 光油/GP-LED 啞油', 'SY6+系列', NULL, 4, TRUE, 'GP-LED 光油/GP-LED 哑油印刷兼容性', 'V'),
('GP-LED 光油/GP-LED 啞油', 'SSY6 系列', NULL, 4, TRUE, 'GP-LED 光油/GP-LED 哑油印刷兼容性', 'V'),
('GP-LED 光油/GP-LED 啞油', 'G1 系列', NULL, 4, TRUE, 'GP-LED 光油/GP-LED 哑油印刷兼容性', 'V'),
('GP-LED 光油/GP-LED 啞油', 'SA 系列', NULL, 4, TRUE, 'GP-LED 光油/GP-LED 哑油印刷兼容性', 'V'),
('GP-LED 光油/GP-LED 啞油', 'SB 系列', NULL, 4, TRUE, 'GP-LED 光油/GP-LED 哑油印刷兼容性', 'V'),
('GP-LED 光油/GP-LED 啞油', 'TA', NULL, 4, TRUE, 'GP-LED 光油/GP-LED 哑油印刷兼容性', 'V'),
('GP-LED 光油/GP-LED 啞油', 'TB', NULL, 4, TRUE, 'GP-LED 光油/GP-LED 哑油印刷兼容性', 'V'),
('GP-LED 光油/GP-LED 啞油', 'S19 系列', NULL, 4, TRUE, 'GP-LED 光油/GP-LED 哑油印刷兼容性', 'V'),
('GP-LED 光油/GP-LED 啞油', 'A19', NULL, 4, TRUE, 'GP-LED 光油/GP-LED 哑油印刷兼容性', 'V'),
('GP-LED 光油/GP-LED 啞油', 'AF', NULL, 4, TRUE, 'GP-LED 光油/GP-LED 哑油印刷兼容性', 'V'),
('GP-LED 光油/GP-LED 啞油', 'SP', NULL, 4, TRUE, 'GP-LED 光油/GP-LED 哑油印刷兼容性', 'V'),
('GP-LED 光油/GP-LED 啞油', 'KA 系列', NULL, 4, TRUE, 'GP-LED 光油/GP-LED 哑油印刷兼容性', 'V'),
('GP-LED 光油/GP-LED 啞油', 'KB 系列', NULL, 4, TRUE, 'GP-LED 光油/GP-LED 哑油印刷兼容性', 'V'),
('GP-LED 光油/GP-LED 啞油', 'L817/GB系列', NULL, 4, TRUE, 'GP-LED 光油/GP-LED 哑油印刷兼容性', 'V'),
('GP-LED 光油/GP-LED 啞油', 'E8系列', NULL, 4, TRUE, 'GP-LED 光油/GP-LED 哑油印刷兼容性', 'V'),
('GP-LED 光油/GP-LED 啞油', 'ST系列', NULL, 4, TRUE, 'GP-LED 光油/GP-LED 哑油印刷兼容性', 'V'),
('GP-LED 光油/GP-LED 啞油', 'SST 系列', NULL, 4, TRUE, 'GP-LED 光油/GP-LED 哑油印刷兼容性', 'V'),
('GP-LED 光油/GP-LED 啞油', 'GN 系列', NULL, 4, TRUE, 'GP-LED 光油/GP-LED 哑油印刷兼容性', 'V'),
('GP-LED 光油/GP-LED 啞油', 'GN2 系列', NULL, 4, TRUE, 'GP-LED 光油/GP-LED 哑油印刷兼容性', 'V'),
('GP-LED 光油/GP-LED 啞油', 'TB815系列', NULL, 4, TRUE, 'GP-LED 光油/GP-LED 哑油印刷兼容性', 'V'),
('GP-LED 光油/GP-LED 啞油', 'LA 系列', NULL, 4, TRUE, 'GP-LED 光油/GP-LED 哑油印刷兼容性', 'V'),
('GP-LED 光油/GP-LED 啞油', 'LLW 系列', NULL, 4, TRUE, 'GP-LED 光油/GP-LED 哑油印刷兼容性', 'V'),
('GP-LED 光油/GP-LED 啞油', 'LLO 系列', NULL, 4, TRUE, 'GP-LED 光油/GP-LED 哑油印刷兼容性', 'V'),
('GP-LED 光油/GP-LED 啞油', 'KM 系列', NULL, 4, TRUE, 'GP-LED 光油/GP-LED 哑油印刷兼容性', 'V'),
('GP-LED 光油/GP-LED 啞油', 'G6系列', NULL, 4, TRUE, 'GP-LED 光油/GP-LED 哑油印刷兼容性', 'V'),
('GP-LED 光油/GP-LED 啞油', 'API 系列', NULL, 4, TRUE, 'GP-LED 光油/GP-LED 哑油印刷兼容性', 'V'),
('GP-LED 光油/GP-LED 啞油', 'V系列', NULL, 4, TRUE, 'GP-LED 光油/GP-LED 哑油印刷兼容性', 'V'),
('GP-LED 光油/GP-LED 啞油', 'VB系列', NULL, 4, TRUE, 'GP-LED 光油/GP-LED 哑油印刷兼容性', 'V'),
('GP-LED 光油/GP-LED 啞油', 'YZT 鐳射系列', NULL, 4, TRUE, 'GP-LED 光油/GP-LED 哑油印刷兼容性', 'V'),
('GP-LED 光油/GP-LED 啞油', 'YZT 普通系列', NULL, 4, TRUE, 'GP-LED 光油/GP-LED 哑油印刷兼容性', 'V'),

-- 去塑油 - 所有系列不兼容
('去塑油', 'SY1-系列', NULL, 5, TRUE, '去塑油印刷兼容性', 'X'),
('去塑油', 'SY6-系列', NULL, 5, TRUE, '去塑油印刷兼容性', 'X'),
('去塑油', 'SY6 系列', NULL, 5, TRUE, '去塑油印刷兼容性', 'X'),
('去塑油', 'SY6+系列', NULL, 5, TRUE, '去塑油印刷兼容性', 'X'),
('去塑油', 'SSY6 系列', NULL, 5, TRUE, '去塑油印刷兼容性', 'X'),
('去塑油', 'G1 系列', NULL, 5, TRUE, '去塑油印刷兼容性', 'X'),
('去塑油', 'SA 系列', NULL, 5, TRUE, '去塑油印刷兼容性', 'X'),
('去塑油', 'SB 系列', NULL, 5, TRUE, '去塑油印刷兼容性', 'X'),
('去塑油', 'TA', NULL, 5, TRUE, '去塑油印刷兼容性', 'X'),
('去塑油', 'TB', NULL, 5, TRUE, '去塑油印刷兼容性', 'X'),
('去塑油', 'S19 系列', NULL, 5, TRUE, '去塑油印刷兼容性', 'X'),
('去塑油', 'A19', NULL, 5, TRUE, '去塑油印刷兼容性', 'X'),
('去塑油', 'AF', NULL, 5, TRUE, '去塑油印刷兼容性', 'X'),
('去塑油', 'SP', NULL, 5, TRUE, '去塑油印刷兼容性', 'X'),
('去塑油', 'KA 系列', NULL, 5, TRUE, '去塑油印刷兼容性', 'X'),
('去塑油', 'KB 系列', NULL, 5, TRUE, '去塑油印刷兼容性', 'X'),
('去塑油', 'L817/GB系列', NULL, 5, TRUE, '去塑油印刷兼容性', 'X'),
('去塑油', 'E8系列', NULL, 5, TRUE, '去塑油印刷兼容性', 'X'),
('去塑油', 'ST系列', NULL, 5, TRUE, '去塑油印刷兼容性', 'V'),
('去塑油', 'SST 系列', NULL, 5, TRUE, '去塑油印刷兼容性', 'V'),
('去塑油', 'GN 系列', NULL, 5, TRUE, '去塑油印刷兼容性', 'X'),
('去塑油', 'GN2 系列', NULL, 5, TRUE, '去塑油印刷兼容性', 'X'),
('去塑油', 'TB815系列', NULL, 5, TRUE, '去塑油印刷兼容性', 'X'),
('去塑油', 'LA 系列', NULL, 5, TRUE, '去塑油印刷兼容性', 'X'),
('去塑油', 'LLW 系列', NULL, 5, TRUE, '去塑油印刷兼容性', 'X'),
('去塑油', 'LLO 系列', NULL, 5, TRUE, '去塑油印刷兼容性', 'X'),
('去塑油', 'KM 系列', NULL, 5, TRUE, '去塑油印刷兼容性', 'X'),
('去塑油', 'G6系列', NULL, 5, TRUE, '去塑油印刷兼容性', 'X'),
('去塑油', 'API 系列', NULL, 5, TRUE, '去塑油印刷兼容性', 'X'),
('去塑油', 'V系列', NULL, 5, TRUE, '去塑油印刷兼容性', 'X'),
('去塑油', 'VB系列', NULL, 5, TRUE, '去塑油印刷兼容性', 'X'),
('去塑油', 'YZT 鐳射系列', NULL, 5, TRUE, '去塑油印刷兼容性', 'X'),
('去塑油', 'YZT 普通系列', NULL, 5, TRUE, '去塑油印刷兼容性', 'X'),

-- 油性油 - 所有系列兼容
('油性油-', 'SY1-系列', NULL, 6, TRUE, '油性油印刷兼容性', 'V'),
('油性油', 'SY6-系列', NULL, 6, TRUE, '油性油印刷兼容性', 'V'),
('油性油', 'SY6 系列', NULL, 6, TRUE, '油性油印刷兼容性', 'V'),
('油性油', 'SY6+系列', NULL, 6, TRUE, '油性油印刷兼容性', 'V'),
('油性油', 'SSY6 系列', NULL, 6, TRUE, '油性油印刷兼容性', 'V'),
('油性油', 'G1 系列', NULL, 6, TRUE, '油性油印刷兼容性', 'V'),
('油性油', 'SA 系列', NULL, 6, TRUE, '油性油印刷兼容性', 'V'),
('油性油', 'SB 系列', NULL, 6, TRUE, '油性油印刷兼容性', 'V'),
('油性油', 'TA', NULL, 6, TRUE, '油性油印刷兼容性', 'V'),
('油性油', 'TB', NULL, 6, TRUE, '油性油印刷兼容性', 'V'),
('油性油', 'S19 系列', NULL, 6, TRUE, '油性油印刷兼容性', 'V'),
('油性油', 'A19', NULL, 6, TRUE, '油性油印刷兼容性', 'V'),
('油性油', 'AF', NULL, 6, TRUE, '油性油印刷兼容性', 'V'),
('油性油', 'SP', NULL, 6, TRUE, '油性油印刷兼容性', 'V'),
('油性油', 'KA 系列', NULL, 6, TRUE, '油性油印刷兼容性', 'V'),
('油性油', 'KB 系列', NULL, 6, TRUE, '油性油印刷兼容性', 'V'),
('油性油', 'L817/GB系列', NULL, 6, TRUE, '油性油印刷兼容性', 'V'),
('油性油', 'E8系列', NULL, 6, TRUE, '油性油印刷兼容性', 'V'),
('油性油', 'ST系列', NULL, 6, TRUE, '油性油印刷兼容性', 'V'),
('油性油', 'SST 系列', NULL, 6, TRUE, '油性油印刷兼容性', 'V'),
('油性油', 'GN 系列', NULL, 6, TRUE, '油性油印刷兼容性', 'V'),
('油性油', 'GN2 系列', NULL, 6, TRUE, '油性油印刷兼容性', 'V'),
('油性油', 'TB815系列', NULL, 6, TRUE, '油性油印刷兼容性', 'V'),
('油性油', 'LA 系列', NULL, 6, TRUE, '油性油印刷兼容性', 'V'),
('油性油', 'LLW 系列', NULL, 6, TRUE, '油性油印刷兼容性', 'V'),
('油性油', 'LLO 系列', NULL, 6, TRUE, '油性油印刷兼容性', 'V'),
('油性油', 'KM 系列', NULL, 6, TRUE, '油性油印刷兼容性', 'V'),
('油性油', 'G6系列', NULL, 6, TRUE, '油性油印刷兼容性', 'V'),
('油性油', 'API 系列', NULL, 6, TRUE, '油性油印刷兼容性', 'V'),
('油性油', 'V系列', NULL, 6, TRUE, '油性油印刷兼容性', 'V'),
('油性油', 'VB系列', NULL, 6, TRUE, '油性油印刷兼容性', 'V'),
('油性油', 'YZT 鐳射系列', NULL, 6, TRUE, '油性油印刷兼容性', 'V'),
('油性油', 'YZT 普通系列', NULL, 6, TRUE, '油性油印刷兼容性', 'V');

-- 验证数据插入结果
SELECT 
    'pre_processing_steps' AS table_name,
    COUNT(*) AS record_count
FROM pre_processing_steps;

-- 按兼容性状态统计
SELECT 
    status,
    COUNT(*) AS record_count
FROM pre_processing_steps
GROUP BY status
ORDER BY status;

-- 按金纸系列统计兼容性
SELECT 
    series_name,
    COUNT(*) AS total_combinations,
    COUNT(CASE WHEN status = 'V' THEN 1 END) AS compatible_count,
    COUNT(CASE WHEN status = 'X' THEN 1 END) AS incompatible_count
FROM pre_processing_steps
GROUP BY series_name
ORDER BY series_name;

-- 按步骤名称统计兼容性
SELECT 
    step_name,
    COUNT(*) AS total_combinations,
    COUNT(CASE WHEN status = 'V' THEN 1 END) AS compatible_count,
    COUNT(CASE WHEN status = 'X' THEN 1 END) AS incompatible_count
FROM pre_processing_steps
GROUP BY step_name
ORDER BY step_order;
